### ISSUE TITLE
Failed to download Chromium when install puppeteer, server returned code 400.

### ISSUE THREAD

**Issue by gucong3000** [cnpm/mirrors#198]
```bash
D:\work\gitkraken-i18n (zh-cn -> origin) (gitkraken-i18n@4.0.2)
$ npm i puppeteer

> puppeteer@1.7.0 install D:\work\gitkraken-i18n\node_modules\puppeteer
> node install.js

ERROR: Failed to download Chromium r579032! Set "PUPPETEER_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
Error: Download failed: server returned code 400. URL: https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/579032/chrome-win32.zip
    at response (D:\work\gitkraken-i18n\node_modules\puppeteer\lib\BrowserFetcher.js:207:21)
    at ClientRequest.require.request.res (D:\work\gitkraken-i18n\node_modules\puppeteer\lib\BrowserFetcher.js:264:7)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:543:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN gitkraken-i18n@4.0.2 No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! puppeteer@1.7.0 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the puppeteer@1.7.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\cdyf\AppData\Roaming\npm-cache\_logs\2018-08-24T10_36_10_023Z-debug.log

```

**Comment by fengmk2** [comment]
https://npm.taobao.org/mirrors/chromium-browser-snapshots/Win_x64/579032/chrome-win32.zip

It can be download for me.
